/*
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation. For the full
 * license text, see http://www.gnu.org/licenses/lgpl.html.
 */
package de.joergjahnke.jdesktopsearch;

import java.util.Observable;
import java.util.Observer;


/**
 * A panel that shows the progress of an indexing operation
 *
 * @author Jörg Jahnke (joergjahnke@users.sourceforge.net)
 */
public class IndexingStatusPanel extends javax.swing.JPanel implements Observer {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	// number of files the dialog was notified of
    private volatile int filesObserved = 0;

    
    /**
     * Creates new form IndexingStatusPanel
     */
    public IndexingStatusPanel() {
        initComponents();
        this.jProgressBar.setVisible( false );
    }
    
   
    /**
     * Update labels and progress bar
     */
    public void update( final Observable observable, final Object arg ) {
        assert( arg instanceof IndexStatusMessage );
        
        final IndexStatusMessage statusMessage = (IndexStatusMessage)arg;

        // show the message text in the central label
        if( statusMessage.message != null ) {
            this.jLabelMessages.setText( statusMessage.message );
        }
        // update the file count if necessary
        if( statusMessage.fileCount > 0 ) {
            this.filesObserved += statusMessage.fileCount;
            this.jLabelFileCount.setText( new Integer( this.filesObserved ).toString() );
        }
        // check for special events
        switch( statusMessage.event ) {
            // a long operation has started?
            case IndexStatusMessage.EVENT_LONG_OPERATION_STARTED:
                // we show the progress bar and reset the other fields
                this.jProgressBar.setVisible( true );
                this.filesObserved = 0;
                break;
            // a long operation has ended or we need to reset?
            case IndexStatusMessage.EVENT_RESET:
            case IndexStatusMessage.EVENT_LONG_OPERATION_ENDED:
                // we hide the progress bar and clear the text field
                this.jProgressBar.setVisible( false );
                break;
        }
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabelFileCount = new javax.swing.JLabel();
        jLabelMessages = new javax.swing.JLabel();
        jProgressBar = new javax.swing.JProgressBar();

        setLayout(new java.awt.BorderLayout());

        jLabelFileCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFileCount.setText(" ");
        jLabelFileCount.setToolTipText("Displays the number of files that were processed during the current indexing operation");
        jLabelFileCount.setMaximumSize(new java.awt.Dimension(100, 14));
        jLabelFileCount.setMinimumSize(new java.awt.Dimension(50, 14));
        jLabelFileCount.setPreferredSize(new java.awt.Dimension(50, 14));
        add(jLabelFileCount, java.awt.BorderLayout.WEST);

        jLabelMessages.setToolTipText("Display information messages about the indexing process");
        add(jLabelMessages, java.awt.BorderLayout.CENTER);

        jProgressBar.setToolTipText("Indicates that indexing is in progress");
        jProgressBar.setIndeterminate(true);
        jProgressBar.setPreferredSize(new java.awt.Dimension(50, 18));
        add(jProgressBar, java.awt.BorderLayout.EAST);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelFileCount;
    private javax.swing.JLabel jLabelMessages;
    private javax.swing.JProgressBar jProgressBar;
    // End of variables declaration//GEN-END:variables
}
